### ISSUE TITLE
3D printing model assembly challenge: central axis installation difficulties

### ISSUE THREAD

**Issue by xinmiti** [TRD-B/Crawler-V5#1]
Firstly, thank you very much for sharing your work. Your design is very cool, which is also my original intention to print it. I am deeply impressed by your clever component segmentation design during the assembly process. At present, most of my car printing parts have been assembled, but I have encountered some problems.

![172963b6dbc4fd498bc4430cd825c79](https://github.com/user-attachments/assets/81884c6f-b1eb-43fa-9b5a-3d49eed572df)
In the attached figure, you can see the three colors indicated by arrows: blue for screws, yellow for nuts, and red for 3mm shafts. When I inserted the M3 nuts on both sides, I found that the central axis could not pass through. I tried to forcefully separate the two sides because there was a ball head and a nut, but it still couldn't be installed. At present, only one side of the nut and screw are installed, but the other side cannot be installed. May I ask how you installed this part?

Also, I haven't started assembling the electronic circuit components yet. Some components in your design cannot be purchased in my country, so I may need to design and implement the control circuit myself, which may take some time. Here are some pictures of my completed work, hoping to share them with you.

![微信图片_20241031090030](https://github.com/user-attachments/assets/5877ffae-b869-447f-9cb3-8789d38b02d2)
![微信图片_20241031101128](https://github.com/user-attachments/assets/1fa5c8ae-0594-48eb-854a-7c6c39bc2768)
![微信图片_20241031101211](https://github.com/user-attachments/assets/a47b96da-dc83-444b-860d-4885e8651b90)
![微信图片_20241031101217](https://github.com/user-attachments/assets/742c44d5-4b09-4f51-a9b3-e88838c6031a)

**Comment by TRD-B** [comment]
Hi xinmiti,

Wow, your build looks already amazing, thanks for sharing! 

At the indicated part, you don't use a 3 mm steel rod plus two M3 screws but only two M3x25 screws (they need to be fully threaded), just like the connection between the wishbone and the main body.

Let me know if you need further input! I'm happy to help!

**Comment by xinmiti** [comment]
> 嗨 xinmiti，
> 
> 哇，您正在构建列表，谢谢分享！
> 
> 在指示的部分，您不要使用3毫米钢棒加两个M3螺钉，而只使用两个M3x25螺钉（它们需要完全螺纹连接），就像叉骨和主体之间的连接一样。
> 
> 如果您需要更多信息，请告诉我！我很乐意提供帮助！

Thank you very much for your reply and answer. I completely understand. It seems that I misunderstood, haha

**Comment by TRD-B** [comment]
Perfect, so I'll close this issue. Just open a new one or leave a comment on Instructables if you have any further questions!
